# Python Container Configuration
dockerUser: geoffh1977
dockerUserEmail: geoffh1977@gmail.com
license: gnu-gpl-v3.0

# Source Image Variables
buildImageName: python3
buildImageVersion: latest

# Final Image Variables
finalImageName: aws
finalImageVersion: latest
appName: AWS
